# Generated by Django 2.2.6 on 2019-10-22 07:39

from django.db import migrations, models
from django.core.management import call_command

import django.utils.timezone
import model_utils.fields


def create_initial_roles(apps, schema_editor):
    call_command('update_or_create_roles')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExORole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(
                    choices=[('SHC', 'Head Coach'), ('SSC', 'Sprint Coach'),
                             ('SAS', 'Awake Speaker'), ('SAT', 'Align Trainer'), ('SAD', 'Advisor')],
                    max_length=3, unique=True)),
                ('category', models.CharField(choices=[
                 ('SP', 'ExO Sprint'), ('FA', 'Fastrack'), ('WO', 'Workshop'),
                 ('SW', 'Swarm'), ('SU', 'Summit')], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('code', 'category')},
            },
            bases=(models.Model,),
        ),
        migrations.RunPython(
            code=create_initial_roles,
        ),
    ]
