# Generated by Django 2.2.6 on 2019-10-23 08:01

from django.db import migrations, models
from django.core.management import call_command

import django.utils.timezone
import model_utils.fields


def create_initial_roles(apps, schema_editor):
    call_command('update_or_create_roles')


class Migration(migrations.Migration):

    dependencies = [
        ('exo_role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(
                    choices=[('CEA', 'ExO Ambassador'), ('CBA', 'ExO Board Advisor'), ('CCO', 'ExO Consultant'),
                             ('CFO', 'ExO Foundations'), ('CSC', 'ExO Sprint Coach'), ('CTR', 'ExO Trainer')],
                    max_length=3, unique=True)),
                ('level', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CertificationRole',
                'verbose_name_plural': 'CertificationRoles',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_initial_roles),
    ]
