sudo: false
dist: xenial
language: python
python: 3.7
matrix:
  fast_finish: true
services:
  - postgresql
install:
  - pip install -r requirements_test.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: 60474827-33ca-48ed-bc0b-82e2d4b4ef24
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJDYwNDc0ODI3LTMzY2EtNDhlZC1iYzBiLTgyZTJkNGI0ZWYyNAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgQGvq_j3B1hn69OyFUN9ngKbxjD5PFohB8qcTTqRIXU4
  on:
    tags: true
    repo: exolever/django-exorole
    python: 3.7
after_success:
  - codecov
