sudo: false
dist: xenial
language: python
python: 3.7
matrix:
  fast_finish: true
services:
  - postgresql
install:
  - pip install -r requirements_test.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: yM8dVSypUEwO7nAY4TDxzjuKiDCILynUy63670SHH0lorr8djrY9QNBsmjBMQ8oXdIqPBTH4tigd38tKFw/9rGwEmH4Z4w7qirDhd8TKDh1poDtEi+yPY3BO335ACpeNUsSSSXiVVeWajqxpFEfdyLfZm9x2EkFWYkUQRzbEgFlhxvY863XxxRwQ3RphR1aIcuAiEbbHgDe1b4b5+EwiORwdeLe7stCpUvkGK90u+H0dNN4R1xZQO1gPZ3tdp1XE/Ozef1H9a+DdRO5Fc/roM3jABEFTqr8e67i5qiw8YcAGcgvVwPSuFqJoZMISjJeURs59StG/bcl6aC0a+oP1GXOC2uu0nKt7J+wAOigmJHVu0XGWl6qmIlnykBo7V7MC6/UsjjkrUenfwTI0uF5UCE/mcd3qaaOCeodApuLxt7/XA2x3jESfmpmzwJx8vOvBmoePSF0LbZ+OARSPve25D8ULqBQfPhqUoMyY8c6Z9Vy9PV3rTYehre6g7A3ZmNYbFbSy1SfcO97KBo9SWRkp0JpIRO3hBezHKJkLyxTjU0jCq5+/cE+TAYUFOuMfy5BPtH/+DQ7e17MhwGiAWQnPVRR+IdMOUofO9ZFKBvXu6eTVmjhSqK0IlB0tYO+MZHwGT5PGX5TMDqaOp7+VQF0NzAvcrvtvKwpSF8sl5KjMusE=
  on:
    tags: true
    repo: exolever/django-exo-role
    python: 3.7
after_success:
  - codecov
